---
# Set up apache vhosts
- name: copy virtual host setup over
  template: src=vhost.conf dest=/etc/apache2/sites-available/

- name: copy apache envars
  template: src=envvars dest=/etc/apache2/

- name: activate virtual host
  command: a2ensite vhost
  notify: Restart apache

- name: disable default virtual host
  command: a2dissite 000-default
  notify: Restart apache


# Set up database and seed with {{ mysql_dbname }}.sql (via a handler)
- name: Setup MySQL user
  mysql_user: name={{ mysql_username }} password={{ mysql_password }} host={{ item }} priv={{ mysql_dbname }}.*:ALL state=present
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost

- name: Give permissions to {{ mysql_username }} for phpmyadmin configuration tables
  mysql_user: >
    name={{ mysql_username }} password={{ mysql_password }} host={{ item }}
    append_privs=yes priv=phpmyadmin.*:ALL state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: create {{ mysql_dbname }} database
  mysql_db: >
    name={{ mysql_dbname }} encoding=utf8 collation=utf8_unicode_ci
    login_user=root login_password={{ mysql_root_password }} state=present
  notify: Import database

